apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: usvc9eq9z-go-gitops
  description: This is GitOps manifest for usvc9eq9z-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=usvc9eq9z-go
    backstage.io/kubernetes-id: usvc9eq9z-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: usvc9eq9z-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:usvc9eq9z-go
